### ISSUE TITLE
Centralize bash scripts in `/scripts` directory

### ISSUE THREAD

**Issue by iknite** [BBVA/qed#103]
All the scripts now live in `/tests` directory and since we are using it as a canonical way to launch environments sometimes outside tests scope (QA, Performance...) I believe it would be worthy to give them a proper directory.

**Comment by suizman** [comment]
Definitely we should clean `/tests` directory and move shell scripts to a proper place.

**Comment by iknite** [comment]
Closing in favor of #119 (`/scripts` is now `/deploy/local` which it doesn't follow the standard go layout but it's better than `/tests`)
