### ISSUE TITLE
Find a semantic name for `function f()`

### ISSUE THREAD

**Issue by iknite** [BBVA/qed#112]
EventMarshalling, or StreamSanitizer or....

**Comment by gdiazlo** [comment]
Can you add some context to this issue?

**Comment by iknite** [comment]
AFAIK `f()` is a piece of code that has been made for users in the shape of a pattern adapter, in order to add any data stream as QED events in the server. So to me it is too much of inexplicit name.

**Comment by gdiazlo** [comment]
You're talking about a concept, not an implementation. We have a document for that.

**Comment by iknite** [comment]
Closing and moving to Docs
