### ISSUE TITLE
Move restore validation to upper layer

### ISSUE THREAD

**Issue by aalda** [BBVA/qed#152]
We should remove the ValidateF function from the LoadSnapshot signature in the ManagedStore and put it in an upper layer,  ¿maybe the ChunkWriter?

In this way, we achieve two things: on the one hand, we separate a functionality related to the FSM from the pure persistence layer; on the other, we check the existence of gaps in the source node before sending the stream of transactions to the replica.

**Comment by gdiazlo** [comment]
Closed by #171
