### ISSUE TITLE
Design / explore how to publish signed snapshots

### ISSUE THREAD

**Issue by gdiazlo** [BBVA/qed#21]
We need to design and implement a way to publish signed snapshot. In order to select a given design, we need to explore multiple options and state which one is the most convenient for our needs.

**Comment by iknite** [comment]
Assigned to @jllucas since the signer it's now in `publishing - publisher` components

**Comment by gdiazlo** [comment]
Agents are already part of our code and design. We need to document it more, but this issue can be closed.
