### ISSUE TITLE
Investigate performance drop

### ISSUE THREAD

**Issue by gdiazlo** [BBVA/qed#28]
Seems the latest Go version give us at least a 10% performance impact in unit benchmarks, which is amplified in e2e benchmarks.

We need to read the changes from one verstion to another. We also need to identify which parts of our code are causing this and analyze if we can change anything to mitigate the effect.

**Comment by suizman** [comment]
Strange thing, I was able to reproduce this issue just few times. Once I've updated the dependencies I was unable to reproduce it again.

I've tried couple of times to run the `BenchmarkAddBadger` benchmarks with "clean go install" v1.10.2 & v1.10.3 and the performance is close enough. Some times even better with on v1.10.3.

I've used your [fork](https://github.com/gdiazlo/qed/tree/incremental) for all the tests.

**Comment by panchoh** [comment]
@suizman, I could install linux-4.17.1 to see how it behaves.  Sounds like a plan?

**Comment by suizman** [comment]
Hi @panchoh any new about your test with the v4.17.1?

**Comment by panchoh** [comment]
Hi, @suizman.  I've tried this morning with 4.17.2, and performance is the same as with the previous kernel.

**Comment by panchoh** [comment]
```
pancho@narada:~
▶ uname -a
Linux narada 4.14.49-1-lts #1 SMP Tue Jun 12 16:32:50 CEST 2018 x86_64 GNU/Linux
pancho@narada:~
▶ cd go/src/github.com/bbva/qed/
pancho@narada:~/g/s/g/b/qed|HEAD⚡?
▶ go test -benchmem -run="^\$" github.com/bbva/qed/balloon -bench "^BenchmarkAddBadger\$"
goos: linux
goarch: amd64
pkg: github.com/bbva/qed/balloon
BenchmarkAddBadger-8   	   10000	    371713 ns/op	  157457 B/op	    3111 allocs/op
PASS
ok  	github.com/bbva/qed/balloon	4.231s
pancho@narada:~/g/s/g/b/qed|HEAD⚡?
▶ git checkout master
Previous HEAD position was f822954 wip: refactor: revert Snapshot to its old form
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
pancho@narada:~/g/s/g/b/qed|master✓
▶ go test -benchmem -run="^\$" github.com/bbva/qed/balloon -bench "^BenchmarkAddBadger\$"
goos: linux
goarch: amd64
pkg: github.com/bbva/qed/balloon
BenchmarkAddBadger-8   	   10000	    331992 ns/op	  114587 B/op	    2007 allocs/op
PASS
ok  	github.com/bbva/qed/balloon	3.800s
pancho@narada:~/g/s/g/b/qed|master✓
▶ 
```

**Comment by suizman** [comment]
Hmm, thanks @panchoh! There are few things clear in this issue:

Using different versions of go does not have a a significant performance impact. It seems to be a problem with the recent kernels.

The new code version which on which are working @gdiazlo & @aalda need to be optimized. As you can see right now we have 50% more allocs.

It seems reasonable to put this on hold untill we have the new code optimized then take a deeper dive into what's happening exaclly with the latest kernels..

**Comment by panchoh** [comment]
> It seems reasonable to put this on hold untill we have the new code optimized then take a deeper dive into what's happening exaclly with the latest kernels..

I agree, @suizman.

**Comment by iknite** [comment]
Closes since it's kernel related
