### ISSUE TITLE
Create benchmark suite to test Membership() throughput

### ISSUE THREAD

**Issue by suizman** [BBVA/qed#52]
We need to measure the system Membership throughput because it's a critical parameter for the system operation(the Membership performance is expected to be greater than the write performance, as well as not losing write throughput when both operations are performed simultaneously.)

We should consider the following scenarios:
 - [x] **Single node**:
  - Start a single node
  - Preload N events
  - Query Membership of the N events
  - Perform continuous write load on the leader
  - At the same time, perform Query Membership of the previous N events

      **Multi node:**
 - [x] One Leader & 2 followers{1..2}
  - Start the cluster
  - Preload N events to the leader
  - Query Membership of the N events to follower 1
  - Perform continuous write load on the leader
  - At the same time, perform Query Membership of the previous N events to all the followers

 - [ ] One Leader & 4 followers{1..4}
 - (Same as before)

**Comment by suizman** [comment]
Fixed in 4aad84cde33c9d5e2819fdb41e9cf2a8a15b7e1a

**Comment by panchoh** [comment]
[MONONODE.txt](https://github.com/BBVA/qed/files/2491245/MONONODE.txt)
[MULTINODE2F.txt](https://github.com/BBVA/qed/files/2491246/MULTINODE2F.txt)
[MULTINODE4F.txt](https://github.com/BBVA/qed/files/2491247/MULTINODE4F.txt)

Raw output of the benchmark runs.

**Comment by panchoh** [comment]
[MULTINODE4F10K.txt](https://github.com/BBVA/qed/files/2492510/MULTINODE4F10K.txt)

**Comment by jllucas** [comment]
![benchmark](https://user-images.githubusercontent.com/5269017/47165912-520ce080-d2fb-11e8-9208-e9ab70bf361d.png)

**Comment by panchoh** [comment]
[MULTINODE2F100K.txt](https://github.com/BBVA/qed/files/2492722/MULTINODE2F100K.txt)
[MULTINODE4F100K.txt](https://github.com/BBVA/qed/files/2492723/MULTINODE4F100K.txt)

**Comment by suizman** [comment]
To open change file extension to SVG

[MONONODE-PPROF-1M.txt](https://github.com/BBVA/qed/files/2501757/MONONODE-PPROF-1M.txt)
[MONONODE-PPROF-10K.txt](https://github.com/BBVA/qed/files/2501758/MONONODE-PPROF-10K.txt)
[MONONODE-PPROF-100K.txt](https://github.com/BBVA/qed/files/2501759/MONONODE-PPROF-100K.txt)
[MONONODE-TORCH-1M.txt](https://github.com/BBVA/qed/files/2501760/MONONODE-TORCH-1M.txt)
[MONONODE-TORCH-10K.txt](https://github.com/BBVA/qed/files/2501761/MONONODE-TORCH-10K.txt)
[MONONODE-TORCH-100K.txt](https://github.com/BBVA/qed/files/2501762/MONONODE-TORCH-100K.txt)
