### ISSUE TITLE
Benchmark: Raft behavior while testing Membership() throughput

### ISSUE THREAD

**Issue by jllucas** [BBVA/qed#53]
We need to measure the system write/query performance when using raft replication, and querying only 1 follower (instead of both).

We should consider the following scenarios:
      **Multi node:**
 - [x] One Leader & two followers{1..2}
  - Start the cluster
  - Preload N events to the leader
  - Query Membership of the N events to follower1
  - Perform continuous write load on the leader
  - At the same time, perform Query Membership of the previous N events ONLY to follower 1
(notice that follower 2 is query-load free)

**Comment by suizman** [comment]
Here you can find the results for this test case:

* We've started 1 leader 2 followers
* Preload 100K events
* Query Membership only to follower1 without additional load 
*  While performing continuous write load to the leader perform reads only on follower1

We can observer that the write performance goes down form ~2150/s to ~1950/s while maintaining around 1250/s of reads on the follower1

See attachment below:
[MULTINODE2-READ-FOLLOWER1.txt](https://github.com/BBVA/qed/files/2534098/MULTINODE2-READ-FOLLOWER1.txt)
