### ISSUE TITLE
Unify cli commands

### ISSUE THREAD

**Issue by aalda** [BBVA/qed#6]
We should use a single base command for every interaction with the server, Therefore `server` command should be integrated into `qed`. 

The sub-command hierarchy would be:

```
qed
  |-- start
  |-- stop
  |-- client
            |-- add
            |-- membership
  |-- auditor
```

`start` sub-command will include flags to enable profiling and tampering endpoints, and also for launching the server in background (-d):

```
qed start -d --profiling --tampering
```

**Comment by gdiazlo** [comment]
No
