### ISSUE TITLE
Create benchmark suite to test Incremental() throughput

### ISSUE THREAD

**Issue by jllucas** [BBVA/qed#61]
![incremental_bench](https://user-images.githubusercontent.com/5269017/47783723-c4ba8a80-dd03-11e8-8a2a-7ae2cf60e280.png)

**Comment by suizman** [comment]
**p.d.** the benchmark was executed with our benchmarking tool **tests/riot.go**

**Comment by jllucas** [comment]
Notice:
- Values 100K, 1M, and 10M in 100K-tree case performs the same query (100K, the máximum delta possible). These results are similar.
- The previous statement applies to values 1M and 10M in 10M-tree case.

- Delta "0" is the fastest incremental query possible. It is our baseline.
